/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application.components;

import java.awt.Color;
import javax.swing.JPanel;
import application.logic.Purchasable;
import application.logic.Helpers;

/**
 *
 * @author david
 */
public class PurchasedListItem extends javax.swing.JPanel {
    
    private Purchasable item;
    private int quantity;
    private Boolean selectable;
    private JPanel[] panels;
    /**
     * Creates new form ProfileListItem
     */
    public PurchasedListItem(Purchasable item, int quantity, Boolean selectable) {
        initComponents();
        
        this.panels = new JPanel[] {
            unitaryPricePanel,
            idPanel,
            quantityPanel,
            totalPanel,
            namePanel
        };
        
        this.selectable = selectable;
        this.item = item;
        this.quantity = quantity;
        this.refresh();
    }
    
    public void refresh() {
        this.idLabel.setText(Integer.toString(item.getId()));
        this.nameLabel.setText(item.getName());
        this.unitaryPriceLabel.setText(Double.toString(item.getCost()));
        this.quantityLabel.setText(Integer.toString(this.quantity));
        this.totalLabel.setText(Double.toString(this.quantity * item.getCost()));
    }

    public Purchasable getItem() {
        return item;
    }

    public void setItem(Purchasable item) {
        this.item = item;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idPanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        namePanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        unitaryPricePanel = new javax.swing.JPanel();
        unitaryPriceLabel = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        quantityPanel = new javax.swing.JPanel();
        quantityLabel = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        totalPanel = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(797, 30));
        setMinimumSize(new java.awt.Dimension(797, 30));
        setPreferredSize(new java.awt.Dimension(797, 30));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        idPanel.setBackground(new java.awt.Color(42, 39, 41));
        idPanel.setMaximumSize(new java.awt.Dimension(120, 30));
        idPanel.setMinimumSize(new java.awt.Dimension(120, 30));
        idPanel.setPreferredSize(new java.awt.Dimension(120, 30));
        idPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        idLabel.setForeground(new java.awt.Color(204, 204, 204));
        idLabel.setText("ID");
        idPanel.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        jSeparator10.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);

        namePanel.setBackground(new java.awt.Color(42, 39, 41));
        namePanel.setMaximumSize(new java.awt.Dimension(160, 30));
        namePanel.setMinimumSize(new java.awt.Dimension(160, 30));
        namePanel.setPreferredSize(new java.awt.Dimension(160, 30));
        namePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(204, 204, 204));
        nameLabel.setText("Nombre");
        namePanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, -1));

        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        unitaryPricePanel.setBackground(new java.awt.Color(42, 39, 41));
        unitaryPricePanel.setMaximumSize(new java.awt.Dimension(180, 30));
        unitaryPricePanel.setMinimumSize(new java.awt.Dimension(180, 30));
        unitaryPricePanel.setPreferredSize(new java.awt.Dimension(180, 30));
        unitaryPricePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        unitaryPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        unitaryPriceLabel.setForeground(new java.awt.Color(204, 204, 204));
        unitaryPriceLabel.setText("Precio Unitario");
        unitaryPricePanel.add(unitaryPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, -1));

        jSeparator11.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);

        quantityPanel.setBackground(new java.awt.Color(42, 39, 41));
        quantityPanel.setMaximumSize(new java.awt.Dimension(180, 30));
        quantityPanel.setMinimumSize(new java.awt.Dimension(180, 30));
        quantityPanel.setName(""); // NOI18N
        quantityPanel.setPreferredSize(new java.awt.Dimension(180, 30));
        quantityPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quantityLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        quantityLabel.setForeground(new java.awt.Color(204, 204, 204));
        quantityLabel.setText("Cantidad");
        quantityPanel.add(quantityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, -1));

        jSeparator12.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);

        totalPanel.setBackground(new java.awt.Color(42, 39, 41));
        totalPanel.setMaximumSize(new java.awt.Dimension(140, 30));
        totalPanel.setMinimumSize(new java.awt.Dimension(140, 30));
        totalPanel.setPreferredSize(new java.awt.Dimension(140, 30));
        totalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(204, 204, 204));
        totalLabel.setText("Total");
        totalPanel.add(totalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(idPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(unitaryPricePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(quantityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(totalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(idPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(unitaryPricePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quantityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        if (!this.selectable) return;
        this.setBackground(new Color(86, 82, 85));
        
        for (JPanel panel : this.panels)
            panel.setBackground(new Color(86, 82, 85));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        if (!this.selectable) return;
        this.setBackground(new Color(42, 39, 41));
        
        for (JPanel panel : this.panels)
            panel.setBackground(new Color(42, 39, 41));
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel idPanel;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel namePanel;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JPanel quantityPanel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JPanel totalPanel;
    private javax.swing.JLabel unitaryPriceLabel;
    private javax.swing.JPanel unitaryPricePanel;
    // End of variables declaration//GEN-END:variables
}
