/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application.components;

import java.awt.Color;
import javax.swing.JPanel;
import application.logic.Sale;
import application.logic.Helpers;

/**
 *
 * @author david
 */
public class SalesListItem extends javax.swing.JPanel {
    
    private Sale sale;
    private JPanel[] panels;
    /**
     * Creates new form ProfileListItem
     */
    public SalesListItem(Sale sale) {
        initComponents();
        
        this.panels = new JPanel[] {
            clientIdPanel,
            idPanel,
            paymentMethodPanel,
            totalPanel,
            datePanel
        };
        
        this.sale = sale;
        this.refresh();
    }
    
    public void refresh() {
        this.idLabel.setText(Integer.toString(sale.getId()));
        this.dateLabel.setText(Helpers.formatDate(sale.getDate()));
        this.providerLabel.setText(Integer.toString(sale.getClient().getId()));
        this.paymentMethodLabel.setText(sale.getPaymentMethod().toString());
        this.totalLabel.setText(Double.toString(sale.getTotal()));
    }

    public Sale getSale() {
        return sale;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idPanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        datePanel = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        clientIdPanel = new javax.swing.JPanel();
        providerLabel = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        paymentMethodPanel = new javax.swing.JPanel();
        paymentMethodLabel = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        totalPanel = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(797, 30));
        setMinimumSize(new java.awt.Dimension(797, 30));
        setPreferredSize(new java.awt.Dimension(797, 30));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        idPanel.setBackground(new java.awt.Color(42, 39, 41));
        idPanel.setMaximumSize(new java.awt.Dimension(120, 30));
        idPanel.setMinimumSize(new java.awt.Dimension(120, 30));
        idPanel.setPreferredSize(new java.awt.Dimension(120, 30));
        idPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        idLabel.setForeground(new java.awt.Color(204, 204, 204));
        idLabel.setText("ID");
        idPanel.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        jSeparator10.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);

        datePanel.setBackground(new java.awt.Color(42, 39, 41));
        datePanel.setMaximumSize(new java.awt.Dimension(160, 30));
        datePanel.setMinimumSize(new java.awt.Dimension(160, 30));
        datePanel.setPreferredSize(new java.awt.Dimension(160, 30));
        datePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(204, 204, 204));
        dateLabel.setText("Fecha");
        datePanel.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, -1));

        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        clientIdPanel.setBackground(new java.awt.Color(42, 39, 41));
        clientIdPanel.setMaximumSize(new java.awt.Dimension(180, 30));
        clientIdPanel.setMinimumSize(new java.awt.Dimension(180, 30));
        clientIdPanel.setPreferredSize(new java.awt.Dimension(180, 30));
        clientIdPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        providerLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        providerLabel.setForeground(new java.awt.Color(204, 204, 204));
        providerLabel.setText("ID Cliente");
        clientIdPanel.add(providerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, -1));

        jSeparator11.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);

        paymentMethodPanel.setBackground(new java.awt.Color(42, 39, 41));
        paymentMethodPanel.setMaximumSize(new java.awt.Dimension(180, 30));
        paymentMethodPanel.setMinimumSize(new java.awt.Dimension(180, 30));
        paymentMethodPanel.setName(""); // NOI18N
        paymentMethodPanel.setPreferredSize(new java.awt.Dimension(180, 30));
        paymentMethodPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paymentMethodLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        paymentMethodLabel.setForeground(new java.awt.Color(204, 204, 204));
        paymentMethodLabel.setText("Numero de Elementos");
        paymentMethodPanel.add(paymentMethodLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, -1));

        jSeparator12.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);

        totalPanel.setBackground(new java.awt.Color(42, 39, 41));
        totalPanel.setMaximumSize(new java.awt.Dimension(140, 30));
        totalPanel.setMinimumSize(new java.awt.Dimension(140, 30));
        totalPanel.setPreferredSize(new java.awt.Dimension(140, 30));
        totalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(204, 204, 204));
        totalLabel.setText("Total");
        totalPanel.add(totalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(idPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(datePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(clientIdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(paymentMethodPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(totalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(idPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(datePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clientIdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paymentMethodPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.setBackground(new Color(86, 82, 85));
        
        for (JPanel panel : this.panels)
            panel.setBackground(new Color(86, 82, 85));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.setBackground(new Color(42, 39, 41));
        
        for (JPanel panel : this.panels)
            panel.setBackground(new Color(42, 39, 41));
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel clientIdPanel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel datePanel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel idPanel;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel paymentMethodLabel;
    private javax.swing.JPanel paymentMethodPanel;
    private javax.swing.JLabel providerLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JPanel totalPanel;
    // End of variables declaration//GEN-END:variables
}
