/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application.views;

import application.DesktopApplication;
import application.logic.DatabaseManager;
import application.logic.Helpers;
import application.logic.MySecurityManager;
import application.logic.Profile;
import java.awt.CardLayout;
import java.io.File;
import java.util.Arrays;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author david
 */
public class ProfileMenu extends javax.swing.JPanel {

    private Profile profile;
    private String profileImagePath;
    /**
     * Creates new form Home
     */
    public ProfileMenu() {
        initComponents();
        
        this.profile = DesktopApplication.getInstance().getCurrentProfile();
        this.refresh();
    }

    public void refresh() {
        this.imageField1.setIcon(Helpers.readIconFromFile(new File(this.profile.getPersonel().getImagePath())));
        this.imageField2.setIcon(Helpers.readIconFromFile(new File(this.profile.getPersonel().getImagePath())));
        this.nameLabel.setText(this.profile.getPersonel().getName());
        this.emailLabel.setText(this.profile.getPersonel().getEmail());
        this.phoneNumberLabel.setText(Integer.toString(this.profile.getPersonel().getPhoneNumber()));
        this.birthdayLabel.setText(Helpers.formatDate(this.profile.getPersonel().getBirthDay()));
        this.admissionDateLabel.setText(Helpers.formatDate(this.profile.getPersonel().getAdmissionDate()));
        this.jobLabel.setText(this.profile.getPersonel().getType().toString());
        this.usernameLabel.setText(this.profile.getUsername());
        this.passwordField.setText("");
        this.confirmationField.setText("");
        this.nameTextField.setText(this.profile.getPersonel().getName());
        this.emailTextField.setText(this.profile.getPersonel().getEmail());
        this.phoneNumberTextField.setText(Integer.toString(this.profile.getPersonel().getPhoneNumber()));
        this.birthdayChooser.setDate(this.profile.getPersonel().getBirthDay());
        this.usernameTextField.setText(this.profile.getUsername());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imageField1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        admissionDateLabel = new javax.swing.JLabel();
        birthdayLabel = new javax.swing.JLabel();
        jobLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        setPictureButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        imageField2 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        phoneNumberTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        birthdayChooser = new com.toedter.calendar.JDateChooser();
        confirmationField = new javax.swing.JPasswordField();
        passwordField = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(960, 610));
        setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imageField1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/504-5040528_empty-profile-picture-png-transparent-png.png"))); // NOI18N
        jPanel1.add(imageField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 330, 390));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Mi Perfil");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 120, 40));

        editButton.setBackground(new java.awt.Color(42, 39, 41));
        editButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        editButton.setForeground(new java.awt.Color(204, 204, 204));
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/edit.png"))); // NOI18N
        editButton.setText("Editar");
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                editButtonMouseReleased(evt);
            }
        });
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel1.add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 160, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nombre de Usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 150, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Correo Electrónico:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 160, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Fecha de Nacimiento:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 160, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Fecha de Ingreso:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 150, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Número de Teléfono:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 350, 20));

        usernameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameLabel.setText("NULL");
        jPanel1.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 460, 20));

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailLabel.setText("NULL");
        jPanel1.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 460, 20));

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("David Eduardo Diaz de Moya");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 520, 30));

        admissionDateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        admissionDateLabel.setText("NULL");
        jPanel1.add(admissionDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 480, 20));

        birthdayLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        birthdayLabel.setText("NULL");
        jPanel1.add(birthdayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 470, 20));

        jobLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jobLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jobLabel.setText("Gerente");
        jPanel1.add(jobLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 310, 20));

        phoneNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneNumberLabel.setText("NULL");
        jPanel1.add(phoneNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 490, 20));

        add(jPanel1, "seeProfile");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setPictureButton.setBackground(new java.awt.Color(42, 39, 41));
        setPictureButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setPictureButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/edit.png"))); // NOI18N
        setPictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPictureButtonActionPerformed(evt);
            }
        });
        jPanel2.add(setPictureButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Mi Perfil");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 120, 40));

        cancelButton.setBackground(new java.awt.Color(42, 39, 41));
        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(204, 204, 204));
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 160, 50));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Correo Electrónico:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 160, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Fecha de Nacimiento:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 160, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Nombre Completo:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 150, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Número de Teléfono:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 350, 20));

        imageField2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/504-5040528_empty-profile-picture-png-transparent-png.png"))); // NOI18N
        jPanel2.add(imageField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 330, 390));

        usernameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 410, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Nombre de Usuario:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 150, 20));

        emailTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 410, 30));

        phoneNumberTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(phoneNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 410, 30));

        nameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 370, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Cambiar Contraseña:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 150, 20));

        confirmButton.setBackground(new java.awt.Color(42, 39, 41));
        confirmButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(204, 204, 204));
        confirmButton.setText("Confirmar Cambios");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        jPanel2.add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 160, 50));
        jPanel2.add(birthdayChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 410, 30));

        confirmationField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmationField.setPreferredSize(new java.awt.Dimension(410, 30));
        jPanel2.add(confirmationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        passwordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordField.setPreferredSize(new java.awt.Dimension(410, 30));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        jPanel2.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        add(jPanel2, "editProfile");
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        ((CardLayout) this.getLayout()).show(this, "editProfile");
        this.profileImagePath = this.profile.getPersonel().getImagePath();
    }//GEN-LAST:event_editButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        ((CardLayout) this.getLayout()).show(this, "seeProfile");
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void editButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseReleased

    }//GEN-LAST:event_editButtonMouseReleased

    private void setPictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPictureButtonActionPerformed
        JFileChooser choice = new JFileChooser();
        choice.addChoosableFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "png", "gif", "jpeg"));
        choice.setAcceptAllFileFilterUsed(false);

        if (choice.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            this.profileImagePath = choice.getSelectedFile().getAbsolutePath();
            this.imageField2.setIcon(Helpers.readIconFromFile(choice.getSelectedFile()));
        }
    }//GEN-LAST:event_setPictureButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        if (this.passwordField.getPassword().length > 0) {
            if (!MySecurityManager.getInstance().comparePasswords(this.passwordField.getPassword(), this.confirmationField.getPassword())) {
                JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            this.profile.setPasswordHash(MySecurityManager.getInstance().hash(this.passwordField.getPassword()));
        }
        
        this.profile.setUsername(this.usernameTextField.getText());
        this.profile.getPersonel().setEmail(this.emailTextField.getText());
        this.profile.getPersonel().setPhoneNumber(Helpers.tryParseInt(this.phoneNumberTextField.getText()));
        this.profile.getPersonel().setBirthDay(this.birthdayChooser.getDate());
        this.profile.getPersonel().setName(this.nameTextField.getText());
        this.profile.getPersonel().setImagePath(this.profileImagePath);
        DatabaseManager.updateProfile(this.profile);
        this.refresh();
        ((CardLayout) this.getLayout()).show(this, "seeProfile");
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admissionDateLabel;
    private com.toedter.calendar.JDateChooser birthdayChooser;
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JPasswordField confirmationField;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel imageField1;
    private javax.swing.JLabel imageField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jobLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JButton setPictureButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
